# Generated by Django 2.1.7 on 2019-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='password2',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
